### ISSUE TITLE
Remove `util` and `EventEmitter`

### ISSUE THREAD

**Issue by twolfson** [chevett/absolurl#5]
I am very close to using this library. However, it is including a lot of unnecessary weight which is making it a bad idea for the browser (via `browserify`). The `util` (unused) and `EventEmitter` require add on 7kb gzipped.

``` bash
# With `util/EventEmitter`
$ ./node_modules/.bin/browserify index.js | gzip | wc --bytes
21075

# Without `util/EventEmitter`
$ ./node_modules/.bin/browserify index.js | gzip | wc --bytes
14472
```

There is no need for `EventEmitter`. This is a synchronous function, not a stream. It should be throwing errors. If it were a stream, then there would be `data` and `end` events in addition to the `error` event.

**Comment by twolfson** [comment]
Sorry, I gave unwanted metrics before. It is gzipped + minified size we care about:

```bash
# With `util/EventEmitter`
$ ./node_modules/.bin/browserify index.js | ./node_modules/.bin/uglifyjs | gzip | wc --bytes
11774

# Without `util/EventEmitter`
$ ./node_modules/.bin/browserify index.js | ./node_modules/.bin/uglifyjs | gzip | wc --bytes
7524
```

**Comment by chevett** [comment]
Ah fair enough,  I'll give this a shot tonight and let you know.

**Comment by twolfson** [comment]
I already wrote another library actually =/ I will post a link when I am done releasing it.

**Comment by chevett** [comment]
Ok

**Comment by chevett** [comment]
it was extremely straightforward to pull out eventemitter.  v2.0.0 is available if you'd like.

**Comment by twolfson** [comment]
Glad to hear =)

Our library has been released as well: https://github.com/underdogio/resolve-link

**Comment by chevett** [comment]
resolve-link doesn't appear to work as I'd expect with these.  Is your intention to build an absolute url?

console.dir(resolveLink('news', 'http://google.com/news/')); 
console.dir(resolveLink('news', 'google.com/news/'));
console.dir(resolveLink('default.aspx', 'google.com/news/'));
console.dir(resolveLink('/wtf', 'google.com/news/'));
console.dir(resolveLink('file.txt', 'google.com'));
console.dir(resolveLink('sky.net', 'http://google.com'));

**Comment by twolfson** [comment]
Yep, the goal is to always build an absolute URL. The second parameter should always be a complete URL.

For reference, these are the results I got:

```js
> console.dir(resolveLink('news', 'http://google.com/news/'));
'http://google.com/news'
> console.dir(resolveLink('news', 'google.com/news/'));
'news'
> console.dir(resolveLink('default.aspx', 'google.com/news/'));
'http://default.aspx/'
> console.dir(resolveLink('/wtf', 'google.com/news/'));
'/wtf'
> console.dir(resolveLink('file.txt', 'google.com'));
'http://file.txt/'
> console.dir(resolveLink('sky.net', 'http://google.com'));
'http://sky.net/'
```

When I moved all of the second parts to absolute URLs, I got results that I would expect.

```js
> console.dir(resolveLink('news', 'http://google.com/news/'));
'http://google.com/news'
> console.dir(resolveLink('news', 'http://google.com/news/'));
'http://google.com/news'
> console.dir(resolveLink('default.aspx', 'http://google.com/news/'));
'http://default.aspx/'
> console.dir(resolveLink('/wtf', 'http://google.com/news/'));
'http://google.com/wtf'
> console.dir(resolveLink('file.txt', 'http://google.com/'));
'http://file.txt/'
> console.dir(resolveLink('sky.net', 'http://google.com/'));
'http://sky.net/'
```

**Comment by chevett** [comment]
oh, i expect different results.  It appears that the results you're expecting are exactly what you'd get from the resolve method of the url module.  

`absolurl` is different from `url.resolve` because it has knowledge of tld names and such.  For example, it knows that file.txt isn't a valid domain, so it always resolves it as a relative url instead of http://file.txt.  `absolurl` is of limited benefit, but it is necessary for a silly project that I'm working on.  

Your resolution of `resolveLink('news', 'http://google.com/news/')` is wrong no matter what a resolver knows.  It should be `http://google.com/news/news`.

Anyway, it seems that `url` or `resolve-url` should do what you're looking for.

```js
> console.dir(resolveLink('news', 'http://google.com/news/'));
'http://google.com/news' //this should be 'http://google.com/news/news'
> console.dir(resolveLink('news', 'http://google.com/news')); // removed trailing slash
//should be 'http://google.com/news'
> console.dir(resolveLink('default.aspx', 'http://google.com/news/'));
'http://default.aspx/' //should be 'http://google.com/news/default.aspx'
> console.dir(resolveLink('/wtf', 'http://google.com/news/'));
'http://google.com/wtf' // correct
> console.dir(resolveLink('file.txt', 'http://google.com/'));
'http://file.txt/' //should be 'http://google.com/file.txt'
> console.dir(resolveLink('sky.net', 'http://google.com/'));
'http://sky.net/' // correct
```

**Comment by twolfson** [comment]
Heh, I thought I was missing a module when I was reviewing my options. I think there is an edge case that I haven't yet reached (e.g. when a username is in a subpath) but I think I will let sleeping dogs lie for now.

**Comment by twolfson** [comment]
Ah, one case I needed a custom library for is when the `srcUrl` lacks a protocol. Then `node's url` seems to treat it as a path =/

```js
> url.resolve('http://github.com/', 'www.google.com')
'http://github.com/www.google.com'
// We want 'http://www.google.com'
> url.parse('www.google.com')
{ protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: null,
  pathname: 'www.google.com',
  path: 'www.google.com',
  href: 'www.google.com' }
```

**Comment by chevett** [comment]
i mean, `www.google.com` is a valid file name.  A dumb file name, but a valid file name.  I think the `url` module functions as it should.  There seems to be a mismatch if you want to handle cases like that, but still resolve to `http://file.txt`.  I suggest adding a simple check to ensure something is a valid url rather than a new library.  As I was saying `absolurl` is a silly library, but it attempts examines all valid tlds and such.

**Comment by twolfson** [comment]
I had a check against valid TLDs in the code. However, it was removed because it added 2kb gzipped/minified when it can be added in as an option later on. I decided to not add that because nobody had requested it yet.

https://github.com/underdogio/resolve-link/blob/1.0.0/lib/resolve-link.js#L17-L19
